
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { AuthContextProvider } from './context/AuthContext'
import { ProductProvider } from './context/ProductContext'
import { CartProvider } from './context/CartContext'
import Page from './page'

const inter = Inter({ subsets: ['latin'] })

// const [clicked, setClicked] = useState(false)

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <CartProvider>
            <ProductProvider>
              <Navbar />
              {children}
            </ProductProvider>
          </CartProvider>
        </AuthContextProvider>

      </body>

    </html>
  )
}
