// "use client";
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import { AuthContextProvider } from './context/AuthContext'
import { ProductProvider } from './context/ProductContext'
import Page from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <ProductProvider>
            <Navbar />
            {children}
          </ProductProvider>
        </AuthContextProvider>

      </body>

    </html>
  )
}
